name: DonutRtp
version: '1.5'
main: smorki.rtp.RTP
api-version: '1.21'
description: DonutRtp Random Teleport Plugin
author: smorki
discord: .smorki
folia-supported: true
softdepend: [LuckPerms]

commands:
  rtp:
  rtpqueue:

permissions:
  rtp.use:
    default: true
  rtp.admin:
    default: op
  rtp.bypass:
    default: op